- name: nodejs | Download source
  get_url:
    url: "{{nodejs_binaries_path}}"
    dest: "{{nodejs_home_path}}"
    mode: 0700
  become: yes
  become_user: node
  register: node_source_downloaded

- name: nodejs | Get node source file name
  shell: find {{nodejs_home_path}} -name 'node-*.tar.gz'
  register: node_source_file_name

- name: nodejs | Unpack the nodejs binaries
  become: yes
  become_user: node
  unarchive:
    src: "{{node_source_file_name.stdout}}"
    dest: "{{nodejs_home_path}}"
    owner: node
    group: node
    mode: 0700

- name: nodejs | Get node unpacked directory name
  set_fact:
    node_source_dir_name: "{{node_source_file_name.stdout.replace('.tar.gz', '')}}"

- name: nodejs | Check node directory stat
  stat:
    path: "{{nodejs_root_path}}"
  register: node_dir

- name: nodejs | Move files into the node directory (overwrite)
  command: cp -TRf {{node_source_dir_name}} {{nodejs_root_path}}
  when: node_dir.stat.exists

- name: nodejs | Rename unpacked files to node directory
  command: mv {{node_source_dir_name}} {{nodejs_root_path}}
  when: not node_dir.stat.exists

- name: nodejs | Delete source directory
  file:
    dest: "{{node_source_dir_name}}"
    state: absent

# @TODO: Find another way to edit this line instead of huge regex
- name: nodejs | Add environment path for node
  lineinfile:
    dest: /etc/environment
    state: present
    backrefs: yes
    regexp: '^PATH=(\"?)((?!.*{{nodejs_bin_path}})[a-zA-Z\:\/]*)(\"?)'
    line: PATH=\1\2:{{nodejs_bin_path}}\3

- name: nodejs | Add NODE_PATH for node_modules
  lineinfile:
    dest: /etc/environment
    state: present
    regexp: 'NODE_PATH'
    line: NODE_PATH="{{nodejs_root_path}}/lib/node_modules"
    insertafter: EOF
